
name: htmldoc19
version: 1.9
summary: HTML and Markdown conversion utility
description: |
  HTMLDOC is a program that reads HTML and Markdown source files or web pages
  and generates corresponding EPUB, HTML, PostScript, or PDF files with an
  optional table of contents.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: desktop/htmldoc-128.png

apps:
    htmldoc:
        command: bin/htmldoc
        desktop: share/applications/htmldoc.desktop
        plugs: [home x11]

parts:
    main:
        plugin: autotools
        source: .

build-packages: [libfltk1.3-dev]
